---
spring:
  application:
    name: spring-cloud-producer
  zipkin:
    base-url: http://localhost:8002
    sleuth:
      sampler:
        percentage: 1.0
server:
  port: 7002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
